
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a          variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[409] =
    {   0,
        0,    0,  100,   98,   66,   64,   97,   96,   98,   98,
       51,   98,    7,    8,   98,   98,   90,   98,   91,   98,
        4,    4,   63,   88,   83,   98,   84,   62,   93,   61,
       61,   67,   68,   53,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       52,   98,    0,    0,   86,    0,    9,    0,    0,   48,
        0,    0,    0,    0,   75,   79,   75,   74,   71,   78,
       74,   73,   72,    4,   77,   73,   69,   76,   76,   76,
       80,   76,    0,    4,    0,   81,   70,   85,   70,   82,
       61,   61,   61,   61,   50,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   43,   16,   60,   60,
        5,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       49,   87,    0,    0,   47,   65,   47,   89,    0,    0,
        0,    0,    0,    1,    3,   47,   61,   61,   42,   54,
       47,   60,   60,   60,   60,   60,   60,   55,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
        0,    0,    0,   95,   94,   94,   61,   61,   10,   60,
       60,    0,    0,   60,   13,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   44,   60,   60,   60,    2,
        6,    0,    0,   41,   40,   11,   60,    0,    0,    0,

       60,   45,   60,   60,   60,   60,   60,   60,   60,   60,
       60,    0,   14,   60,   60,    0,    0,   60,   60,   60,
        0,   60,   59,   60,   57,   46,   60,    0,   60,   60,
        0,    0,   60,   15,   26,    0,    0,   56,   60,    0,
        0,   60,   12,    0,   92,   60,    0,    0,    0,    0,
       60,    0,    0,    0,    0,    0,   60,    0,    0,    0,
        0,    0,    0,   58,    0,    0,    0,    0,    0,   17,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   22,    0,    0,    0,    0,   31,    0,
       24,    0,    0,    0,    0,    0,    0,   35,    0,    0,
        0,    0,    0,   32,    0,   25,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   34,    0,
        0,    0,   23,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   33,   39,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,    0,    0,    0,    0,
       20,    0,    0,    0,    0,    0,   28,    0,    0,    0,
       29,    0,   21,    0,    0,    0,    0,    0,    0,   30,

       36,   19,    0,   37,    0,   27,   38,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   27,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   51,    1,   60,    1,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    1,
        1,    1,    1,    4,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[424] =
    {   0,
        0,    0,  545,  495,   60,  494,  493,  492,   40,   57,
       42,   58,  491,  490,   43,   55,  489,   54,   47,   59,
       65,   79,  488,  487,   51,   52,   56,  486,  485,  484,
       44,  483,  482,   62,   64,   75,   66,  481,   71,   45,
       81,   76,   83,   50,   82,   87,   90,   86,   92,  100,
      121,  133,  477,  526,  546,  138,  546,  524,  140,  546,
      517,  516,  137,   98,  546,  546,  472,  546,  546,  546,
      471,  546,  139,  143,  546,  470,  546,  546,  509,    0,
      546,  468,  137,  147,    0,  546,  546,  546,  467,  546,
        0,  466,  459,  467,  546,    0,  477,  476,  461,  459,

      472,  112,  460,  456,  462,  455,    0,  469,  457,  467,
        0,  459,  459,  465,  446,  451,  443,  454,  453,  447,
      546,  546,  157,  161,  546,  546,  160,  546,  440,  168,
      481,  156,  181,  175,    0,    0,  453,  456,    0,    0,
        0,  451,  454,  434,  170,  448,  433,  446,  438,  428,
      433,  442,  424,  433,  423,  436,  437,  417,  428,  435,
      179,  461,  459,  546,  196,  198,  432,  415,    0,  423,
      424,  446,  439,  416,    0,  424,  427,  406,  402,  406,
      421,  422,  413,  403,  408,    0,  433,  413,  402,  185,
      546,  438,  193,    0,    0,    0,  401,  409,  421,  409,

      403,    0,  407,  405,  422,  383,  386,  385,  401,  389,
      397,  415,    0,  377,  378,  384,  381,  391,  387,  389,
      407,  406,    0,  386,    0,    0,  370,  169,  370,  383,
      367,  370,  367,    0,  398,  171,  397,    0,  367,  366,
      168,  394,    0,  361,  546,  369,  391,  361,  170,  182,
      361,  361,  357,  369,  385,  345,  349,  352,  354,  350,
      362,  349,  173,    0,  347,  347,  349,  351,  373,    0,
      357,  341,  341,  343,  341,  337,  349,  342,  332,  328,
      175,  362,  327,  337,  327,  323,  327,  327,  329,  328,
      319,  334,  321,  333,  319,  326,  321,  312,  327,  321,

      311,  307,  322,  340,  320,  309,  311,  307,  546,  316,
      334,  314,  306,  297,  312,  297,  328,  327,  294,  290,
      301,  291,  322,  321,  301,  319,  299,  317,  286,  315,
      280,  295,  284,  311,  280,  309,  276,  307,  306,  305,
      289,  273,  302,  282,  266,  299,  283,  267,  296,  265,
      294,  273,  258,  276,  290,  289,  546,  268,  253,  271,
      285,  269,  253,  256,  259,  246,  249,  278,  251,  254,
      241,  254,  239,  257,  256,  546,  248,  254,  238,  252,
      546,  244,  239,  242,  229,  241,  546,  227,  245,  238,
      546,  243,  546,  221,  171,  169,  155,  154,  154,  546,

      546,  546,  146,  546,  125,  546,  546,  546,  225,  229,
      233,  237,  241,  245,  249,  251,  253,  257,  261,  171,
      265,  269,  273
    } ;

static yyconst flex_int16_t yy_def[424] =
    {   0,
      408,    1,  408,  408,  408,  408,  408,  408,  408,  409,
      408,  410,  408,  408,  411,  412,  408,  413,  408,  414,
      408,  408,  408,  408,  408,  415,  408,  408,  408,  416,
      416,  408,  408,  408,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      408,  408,  408,  408,  408,  409,  408,  409,  409,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  418,  419,
      408,  408,  408,  408,  420,  408,  408,  408,  408,  408,
      416,  416,  416,  416,  408,  417,  417,  417,  417,  417,

      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      408,  408,  408,  408,  408,  408,  409,  408,  408,  408,
      418,  421,  419,  408,  420,  416,  416,  416,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      408,  408,  422,  408,  408,  419,  416,  416,  417,  417,
      417,  408,  423,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  408,
      408,  422,  421,  416,  416,  417,  417,  408,  423,  408,

      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  408,  417,  417,  417,  408,  408,  417,  417,  417,
      408,  417,  417,  417,  417,  417,  417,  408,  417,  417,
      408,  408,  417,  417,  417,  408,  408,  417,  417,  408,
      408,  417,  417,  408,  408,  417,  408,  408,  408,  408,
      417,  408,  408,  408,  408,  408,  417,  408,  408,  408,
      408,  408,  408,  417,  408,  408,  408,  408,  408,  417,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,    0,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408
    } ;

static yyconst flex_int16_t yy_nxt[608] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   30,   32,
        4,   33,   34,    4,   35,   36,   37,   38,   39,   40,
       38,   38,   41,   38,   38,   42,   43,   38,   44,   45,
       38,   46,   47,   48,   49,   38,   50,   38,   38,   51,
       52,   54,   55,   57,   60,   66,   62,   69,   73,   77,
       79,   74,   74,   86,   88,   80,   75,   70,   90,  105,
       83,   81,   84,   84,   95,  112,   93,   58,   53,   94,
       53,   67,   92,  106,   83,   53,   84,   84,   99,   53,

       89,   97,   76,   71,   53,   59,   63,   82,   53,  100,
       53,   98,   99,   53,  102,  103,  104,  110,  109,   99,
      107,  111,   85,   99,   99,  115,  101,   53,  108,   99,
       99,   99,  116,  113,   99,   99,  114,  117,   99,  118,
       99,  119,  120,  121,   57,  128,   57,  123,   99,  125,
      124,  124,  129,  130,  134,  134,   84,   84,   83,  144,
       84,   84,   83,  141,   84,   84,   57,  132,   58,   53,
       58,  123,  164,  135,  124,  124,  161,  407,  124,  124,
      122,   53,  130,  165,  166,   84,   84,  406,  125,  172,
       58,  127,  134,  134,  405,  173,  190,  190,  165,  165,

      165,  166,  190,  190,  193,  240,  404,  248,  403,  164,
      402,  241,  174,  249,  253,  254,  260,  261,  262,  276,
      277,  293,  294,  401,  263,   56,   56,   56,   56,   61,
       61,   61,   61,   65,   65,   65,   65,   68,   68,   68,
       68,   72,   72,   72,   72,   78,   78,   78,   78,   87,
       87,   87,   87,   91,   91,   96,   96,  131,  131,  131,
      131,  133,  400,  133,  133,  163,  163,  163,  163,  192,
      192,  192,  192,  199,  199,  199,  199,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,

      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  275,  274,  273,

      272,  271,  270,  269,  268,  267,  266,  265,  264,  259,
      258,  257,  256,  255,  252,  251,  250,  247,  246,  245,
      244,  243,  242,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  200,  216,  215,  193,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  198,  197,  196,  195,  194,
      193,  191,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  171,  170,  169,
      168,  167,  132,  162,  160,  159,  158,  157,  156,  155,

      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      143,  142,  141,  140,  139,  138,  137,  136,  125,  125,
      132,  125,  125,  125,   61,  128,  408,  126,  125,   99,
       53,   53,   92,   53,   53,   53,   53,   53,   53,   64,
       53,   53,   53,   53,  408,    3,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408
    } ;

static yyconst flex_int16_t yy_chk[608] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    9,   10,   11,   15,   12,   16,   18,   19,
       20,   18,   18,   25,   26,   20,   18,   16,   27,   40,
       21,   20,   21,   21,   34,   44,   31,   10,    9,   31,
       11,   15,   31,   40,   22,   19,   22,   22,   44,   25,

       26,   35,   18,   16,   27,   10,   12,   20,    5,   36,
       34,   35,   35,   21,   37,   37,   39,   43,   42,   39,
       41,   43,   21,   36,   42,   46,   36,   22,   41,   41,
       45,   43,   47,   45,   48,   46,   45,   48,   47,   49,
       49,   50,   50,   51,   56,   63,   59,   52,   50,   64,
       52,   52,   64,   73,   83,   83,   73,   73,   74,  102,
       74,   74,   84,  102,   84,   84,  127,  132,   56,   51,
       59,  123,  132,  420,  123,  123,  124,  405,  124,  124,
       51,   52,  130,  133,  133,  130,  130,  403,   63,  145,
      127,   59,  134,  134,  399,  145,  161,  161,  165,  165,

      166,  166,  190,  190,  193,  228,  398,  236,  397,  193,
      396,  228,  145,  236,  241,  241,  249,  249,  250,  263,
      263,  281,  281,  395,  250,  409,  409,  409,  409,  410,
      410,  410,  410,  411,  411,  411,  411,  412,  412,  412,
      412,  413,  413,  413,  413,  414,  414,  414,  414,  415,
      415,  415,  415,  416,  416,  417,  417,  418,  418,  418,
      418,  419,  394,  419,  419,  421,  421,  421,  421,  422,
      422,  422,  422,  423,  423,  423,  423,  392,  390,  389,
      388,  386,  385,  384,  383,  382,  380,  379,  378,  377,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,

      365,  364,  363,  362,  361,  360,  359,  358,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  269,  268,  267,  266,  265,  262,  261,  260,

      259,  258,  257,  256,  255,  254,  253,  252,  251,  248,
      247,  246,  244,  242,  240,  239,  237,  235,  233,  232,
      231,  230,  229,  227,  224,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  201,  200,  199,  198,  197,  192,
      189,  188,  187,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  174,  173,  172,  171,  170,  168,  167,
      163,  162,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  144,  143,  142,
      138,  137,  131,  129,  120,  119,  118,  117,  116,  115,

      114,  113,  112,  110,  109,  108,  106,  105,  104,  103,
      101,  100,   99,   98,   97,   94,   93,   92,   89,   82,
       79,   76,   71,   67,   62,   61,   58,   54,   53,   38,
       33,   32,   30,   29,   28,   24,   23,   17,   14,   13,
        8,    7,    6,    4,    3,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
#include <stdio.h>
#include "node.h"
#include "yacc.tab.h"

#ifdef WIN32
#define YY_NO_UNISTD_H
#include <io.h>
#define isatty _isatty
#define fileno _fileno
#define strdup _strdup
#endif

int parseOk;
char* lexErrorText = NULL;
int lexErrorLine = 0;

#define PRINT_TOKEN(a)  /* a */
//#define PRINT_TOKEN(a) printf(a);

void setParseFile(FILE* _parseFile)
{
	yyin = _parseFile;
	parseOk = 1;
}

int isParsingSuccessed()
{
	return parseOk;
}

char* getLexErrorText()
{
	return lexErrorText;
}

int getLexErrorLine()
{
	return lexErrorLine;
}

#line 788 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	         yy_state_type yy_current_state;
	         char *yy_cp, *yy_bp;
	         int yy_act;
    
#line 46 "lex.l"

#line 972 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			         YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 409 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 546 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "lex.l"
PRINT_TOKEN("FP_NUMBER\n"); yylval.strval = strdup(yytext); return FP_NUMBER;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "lex.l"
PRINT_TOKEN("ARB_FP_NUMBER\n"); yylval.strval = strdup(yytext); return FP_ARB_NUMBER;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "lex.l"
PRINT_TOKEN("hex\n"); yylval.strval = strdup(yytext); return HEX_NUMBER;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "lex.l"
PRINT_TOKEN("number\n"); yylval.strval = strdup(yytext); return NUMBER;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "lex.l"
PRINT_TOKEN("ME\n"); return ME;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "lex.l"
PRINT_TOKEN("out\n"); return OUT_SPEC;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "lex.l"
PRINT_TOKEN("parens start\n"); return PARENS_START;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lex.l"
PRINT_TOKEN("parens end\n"); return PARENS_END;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 55 "lex.l"
PRINT_TOKEN("string\n"); yylval.strval = strdup(yytext); return STRING;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "lex.l"
PRINT_TOKEN("base\n"); return BASE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lex.l"
PRINT_TOKEN("break\n"); return BREAK;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "lex.l"
PRINT_TOKEN("continue\n"); return CONTINUE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "lex.l"
PRINT_TOKEN("else\n"); return ELSE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "lex.l"
PRINT_TOKEN("while\n"); return WHILE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "lex.l"
PRINT_TOKEN("foreach\n"); return FOREACH;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "lex.l"
PRINT_TOKEN("foreach\n"); return IN_CONSTRUCT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "lex.l"
PRINT_TOKEN("cpp::inherit\n"); return CPP_INHERIT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "lex.l"
PRINT_TOKEN("unix::import::path\n"); return UNIX_IMPORT_PATH;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "lex.l"
PRINT_TOKEN("windows::import::path\n"); return WINDOWS_IMPORT_PATH;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "lex.l"
PRINT_TOKEN("linux::import::path\n"); return LINUX_IMPORT_PATH;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "lex.l"
PRINT_TOKEN("macosx::import::path\n"); return MACOSX_IMPORT_PATH;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "lex.l"
PRINT_TOKEN("unix::import\n"); return UNIX_IMPORT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "lex.l"
PRINT_TOKEN("windows::import\n"); return WINDOWS_IMPORT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "lex.l"
PRINT_TOKEN("linux::import\n"); return LINUX_IMPORT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "lex.l"
PRINT_TOKEN("macosx::import\n"); return MACOSX_IMPORT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "lex.l"
PRINT_TOKEN("include\n"); return INCLUDE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "lex.l"
PRINT_TOKEN("windows::include::path\n"); return WINDOWS_INCLUDE_PATH;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "lex.l"
PRINT_TOKEN("unix::include::path\n"); return UNIX_INCLUDE_PATH;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "lex.l"
PRINT_TOKEN("linux::include::path\n"); return LINUX_INCLUDE_PATH;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "lex.l"
PRINT_TOKEN("macosx::include::path\n"); return MACOSX_INCLUDE_PATH;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "lex.l"
PRINT_TOKEN("include::path\n"); return INCLUDE_PATH;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 78 "lex.l"
PRINT_TOKEN("linux::include\n"); return LINUX_INCLUDE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "lex.l"
PRINT_TOKEN("windows::include\n"); return WINDOWS_INCLUDE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "lex.l"
PRINT_TOKEN("macosx::include\n"); return MACOSX_INCLUDE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "lex.l"
PRINT_TOKEN("unix::include\n"); return UNIX_INCLUDE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 82 "lex.l"
PRINT_TOKEN("unix::compiler::flags\n"); return UNIX_COMPILER_FLAGS;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 83 "lex.l"
PRINT_TOKEN("linux::compiler::flags\n"); return LINUX_COMPILER_FLAGS;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "lex.l"
PRINT_TOKEN("macosx::compiler::flags\n"); return MACOSX_COMPILER_FLAGS;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 85 "lex.l"
PRINT_TOKEN("cpp::entry::point\n"); return CPP_ENTRY_POINT;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "lex.l"
PRINT_TOKEN("FLOAT\n"); return FLOAT_DECL;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "lex.l"
PRINT_TOKEN("FLOAT\n"); return FIXED_DECL;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 88 "lex.l"
PRINT_TOKEN("add\n"); return ADD_CPP;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "lex.l"
PRINT_TOKEN("if\n"); return IF;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "lex.l"
PRINT_TOKEN("true\n"); return VAL_TRUE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "lex.l"
PRINT_TOKEN("false\n"); return VAL_FALSE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "lex.l"
PRINT_TOKEN("return\n"); return OPERATOR_RETURN;
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 93 "lex.l"
PRINT_TOKEN("or\n"); return OR;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "lex.l"
PRINT_TOKEN("&=\n"); return OPERATOR_AND_EQUAL;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "lex.l"
PRINT_TOKEN("|=\n"); return OPERATOR_OR_EQUAL;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 96 "lex.l"
PRINT_TOKEN("^=\n"); return OPERATOR_XOR_EQUAL;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 97 "lex.l"
PRINT_TOKEN("&\n"); return OPERATOR_MATH_AND;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 98 "lex.l"
PRINT_TOKEN("|\n"); return OPERATOR_MATH_OR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 99 "lex.l"
PRINT_TOKEN("^\n"); return OPERATOR_MATH_XOR;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 100 "lex.l"
PRINT_TOKEN("and\n"); return AND;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 101 "lex.l"
PRINT_TOKEN("for\n"); return FOR;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 102 "lex.l"
PRINT_TOKEN("private\n"); return PRIVATE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 103 "lex.l"
PRINT_TOKEN("public\n"); return PUBLIC;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 104 "lex.l"
PRINT_TOKEN("singleton\n"); return SINGLETON;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 105 "lex.l"
PRINT_TOKEN("object"); return OBJECT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 106 "lex.l"
PRINT_TOKEN("id\n"); yylval.strval = strdup(yytext); return ID_FUNC;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 107 "lex.l"
PRINT_TOKEN("id\n"); yylval.strval = strdup(yytext); return ID_CLASS;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 108 "lex.l"
PRINT_TOKEN("?\n"); return QUESTION_SIGN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 109 "lex.l"
PRINT_TOKEN(":\n"); return COLON;
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 110 "lex.l"
PRINT_TOKEN("newline\n"); return NEWLINE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 111 "lex.l"
PRINT_TOKEN("cd3\n"); return CODE_LEVEL3;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 112 "lex.l"
PRINT_TOKEN("cd\n"); return CODE_LEVEL;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 113 "lex.l"
PRINT_TOKEN("[\n"); return SQUARE_BRACKET_START;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 114 "lex.l"
PRINT_TOKEN("]\n"); return SQUARE_BRACKET_END;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 115 "lex.l"
PRINT_TOKEN("concat\n"); return OPERATOR_CONCAT;
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 116 "lex.l"
PRINT_TOKEN("equal\n"); return OPERATOR_EQUAL;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 117 "lex.l"
PRINT_TOKEN("inc\n"); return OPERATOR_INCREMENT;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 118 "lex.l"
PRINT_TOKEN("dec\n"); return OPERATOR_DECREMENT;
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 119 "lex.l"
PRINT_TOKEN("minus\n"); return OPERATOR_MINUS;
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 120 "lex.l"
PRINT_TOKEN("plus\n"); return OPERATOR_PLUS;
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 121 "lex.l"
PRINT_TOKEN("*\n"); return OPERATOR_MULTIPLY;
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 122 "lex.l"
PRINT_TOKEN("divide\n"); return OPERATOR_DIVISION;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 123 "lex.l"
PRINT_TOKEN("-=\n"); return OPERATOR_MINUS_EQUAL;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 124 "lex.l"
PRINT_TOKEN("+=\n"); return OPERATOR_PLUS_EQUAL;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 125 "lex.l"
PRINT_TOKEN("*=\n"); return OPERATOR_MULTIPLY_EQUAL;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 126 "lex.l"
PRINT_TOKEN("divide equal\n"); return OPERATOR_DIVISION_EQUAL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 127 "lex.l"
PRINT_TOKEN("cmp less eq\n"); return COMPARE_LESS_EQUAL;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 128 "lex.l"
PRINT_TOKEN("cmp more eq\n"); return COMPARE_MORE_EQUAL;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 129 "lex.l"
PRINT_TOKEN("cmp less\n"); return COMPARE_LESS;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 130 "lex.l"
PRINT_TOKEN("cmp more\n"); return COMPARE_MORE;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 131 "lex.l"
PRINT_TOKEN("cmp eq\n"); return COMPARE_EQUAL;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 132 "lex.l"
PRINT_TOKEN("cmp not eq\n"); return COMPARE_NOT_EQUAL;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 133 "lex.l"
PRINT_TOKEN("cond or\n"); return CONDITION_OR;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 134 "lex.l"
PRINT_TOKEN("end part\n"); return END_PART;
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 135 "lex.l"
PRINT_TOKEN("symbol\n"); yylval.strval = strdup(yytext); return SYMBOL;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 136 "lex.l"
PRINT_TOKEN("comma\n"); return COMMA;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 137 "lex.l"
PRINT_TOKEN("dot\n"); return DOT;
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 138 "lex.l"
PRINT_TOKEN("cpp\n"); yylval.strval = strdup(yytext); return CPP;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 139 "lex.l"
PRINT_TOKEN("@"); return DOG;
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 140 "lex.l"
PRINT_TOKEN("comment \n"); yylval.strval = strdup(yytext); return SINGLELINE_COMMENT;
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 141 "lex.l"
PRINT_TOKEN("m comment\n"); yylval.strval = strdup(yytext); return MULTILINE_COMMENT;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 142 "lex.l"
/**/
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 143 "lex.l"
/**/
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 144 "lex.l"
/*printf("FATAL ERROR: unrecognized lexem: %s\n", yytext);*/lexErrorText = strdup(yytext); lexErrorLine = yylineno; parseOk = 0;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 145 "lex.l"
ECHO;
	YY_BREAK
#line 1572 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	         char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	         char *source = (yytext_ptr);
	         int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	         yy_state_type yy_current_state;
	         char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		         YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 409 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	         int yy_is_jam;
    	         char *yy_cp = (yy_c_buf_p);

	         YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 409 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 408);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, char * yy_bp )
{
	         char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		         yy_size_t number_to_move = (yy_n_chars) + 2;
		         char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		         char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	         int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	         int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 144 "lex.l"



